# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
#use_frameworks!
#pod 'CocoaLumberjack'

target 'QQMusic' do
pod 'AFNetworking', '~> 2.5'
pod 'Masonry'
pod 'MJExtension'
end